### ISSUE TITLE
Usage of com.google.common.base.Optional instead of java.util.Optional

### ISSUE THREAD

**Issue by julesjacobsen** [prefixcommons/curie-util#1]
Is this in order to maintain Java 7 compatibility? Is this really worthwhile? Sorry - I should add this is in curie-util/src/main/java/org/prefixcommons/CurieUtil.java

**Comment by cmungall** [comment]
i'm fine to ditch java7 support

**Comment by jnguyenx** [comment]
Okay I'll push an updated version on mvn central.
